config/routes.rb
Rails.application.routes.draw do
 resources :photos do
 	resources :comments
 end

 root 'photos#index'
 
  get 'photos/index'

  get 'photos/show'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :photo
end

app/models/photo.rb
class Photo < ApplicationRecord
	has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
  	@photos = Photo.all.page(params[:page]).per(20)
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/comments/_comment.html.erb
<p><strong><%= comment.username %>:</strong><%= comment.body %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coderphoto</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<nav class="navbar navbar-dark bg-faded" style="border-radius: 0; background-color: #778899">
  		<%= link_to "CoderPhoto", root_path, class: 'navbar-brand' %>
  		<ul class="nav navbar-nav">
  			<li class="nav-item active">
  				<%= link_to "Timeline", photos_path, class: 'nav-link' %>
  			</li>
  		</ul>
  	</nav>

	<div class="jumbotron">
		<h1 class="dislay-3">CoderPhoto</h1>
		<p class="lead"> This is first lab demo of Ruby class</p>
		<hr class="m-y-2">
			<p>I spent 4 hours to make this lab, just complete Milestone 3, haiz! </p>
	</div>


  	<div  class="container"> 
    	<%= yield %>
    </div>
  </body>
</html>

app/views/photos/_photo.html.erb
<div class="card">
		<div class="card-header">
			<div class="avatar">
				<%= image_tag Faker::Avatar.image(photo.username, '32x32') %>
			</div>
			<%= photo.username %>
			<span class="timestamp pull-xs-right"><%= time_ago_in_words photo.created_at %></span>
		</div>
		<%= image_tag(photo.url, class: "card-img") %>
		<p class="card-text"><%= photo.caption %></p>
		<%= pluralize photo.likes_count, 'like' %>

		<div class="card-footer">
			<% photo.comments.each do |comment| %>
				<p><strong><%= comment.username %>:</strong><%= comment.body %></p>
			<% end %>
		</div>	
	</div>

app/views/photos/index.html.erb
<%= paginate @photos %>

<% @photos.each do |photo| %>
	<%= render photo %>
<% end %>

<%= paginate @photos %>

app/views/photos/show.html.erb
<h1>Photos#show</h1>
<p>Find me in app/views/photos/show.html.erb</p>